### ISSUE TITLE
Implementing From Existing Project

### ISSUE THREAD

**Issue by EliterScripts** [rdlaitila/LURE#7]
Hello,
 I haven't really programmed in C, nor am I an expert in web browsing, HTML, CSS, or other web browser languages, but my impression is that this project is trying to reinvent the wheel. Web browsers have already been created, and many people (I am sure) have needed HTML rendered in their applications before.
 I wanted to ask if it were possible to implement Modest, https://github.com/lexborisov/Modest/ , and basically code the "glue" ("bind" might be the official term I'm looking for) between LOVE2D/Lua and an already existing project that might have a lot more backing than what you are currently getting.
 Similarly, people don't (or shouldn't) try to recreate OpenSSL, because it's already been created, tested, used by and worked on by hundreds of people. From my understanding, is that what is a good practice is to code OpenSSL bindings to bring the library/code and make it available to specific needs, not to recode it.

**Comment by rdlaitila** [comment]
The LURE project is nothing more than a toy/experiment. In no way is it intended to compete with existing browsers or other lightweight HTML rendering engines. It is more or less just for fun. 

I'm not finding much time these days to poke at it, but the concept of exploring the complexities of HTML rendering and building some kind of implementation is still interesting to me, so I may at some point make future progress, or maybe not...

As for writing lua to C bindings for https://github.com/lexborisov/Modest/ I would say that work is out of scope for my goals and would be best done by someone with the motivation to maintain such a binding library.

Thanks for the feedback!
